### Feature Engineering 2

In [1]:
from util.data_aquisition import generate

In [2]:
data = generate(seasons=[2015, 2016, 2017, 2018], play_offs=[False])

Data is available on your system. Will be loaded from: /Users/nassimwalha/Desktop/IFT-6758/data/regular_season/2015-2016
Data is available on your system. Will be loaded from: /Users/nassimwalha/Desktop/IFT-6758/data/regular_season/2016-2017
Data is available on your system. Will be loaded from: /Users/nassimwalha/Desktop/IFT-6758/data/regular_season/2017-2018
Data is available on your system. Will be loaded from: /Users/nassimwalha/Desktop/IFT-6758/data/regular_season/2018-2019

#### Create new data frame

In [13]:
import pandas as pd
import numpy as np
import math

In [4]:
Empty_Net = []
Game_ID = []
Game_Type = []
Event_ID = []
Event_Type = []
Power_Game = []
Team_Attack = []
Coordinate_X = []
Coordinate_Y = []
Period = []
Period_Time = []
Time = []
Shooters = []
Scorers = []
Goalies = []
Shoot_type = []
Home = []
Away = []
Home_Rink = []
#Last Event Features
Last_Event_ID = []
Last_Event_Type = []
Last_Coordinate_X = []
Last_Coordinate_Y = []
Last_Period = []
Last_Period_Time = []
Last_Time = []

for a in range(len(data.data)):
    for b in range(len(data.data[a]['data'])):
        for i in range(len(data.data[a]['data'][b]['liveData']['plays']['allPlays'])):
            if data.data[a]['data'][b]['liveData']['plays']['allPlays'][i]['result']['event'] == 'Shot' or data.data[a]['data'][b]['liveData']['plays']['allPlays'][i]['result']['event'] == 'Goal':
                #Features corresponding to last event
                Last_Event_ID.append(data.data[a]['data'][b]['liveData']['plays']['allPlays'][i-1]['about']['eventIdx'])
                Last_Event_Type.append(data.data[a]['data'][b]['liveData']['plays']['allPlays'][i-1]['result']['event'])
                Last_Coordinate_X.append(data.data[a]['data'][b]['liveData']['plays']['allPlays'][i-1]['coordinates'].get('x', np.nan))
                Last_Coordinate_Y.append(data.data[a]['data'][b]['liveData']['plays']['allPlays'][i-1]['coordinates'].get('y', np.nan))
                Last_Period.append(data.data[a]['data'][b]['liveData']['plays']['allPlays'][i-1]['about']['period'])
                Last_Period_Time.append(data.data[a]['data'][b]['liveData']['plays']['allPlays'][i-1]['about']['periodTime'])
                Last_Time.append(data.data[a]['data'][b]['liveData']['plays']['allPlays'][i-1]['about']['dateTime'])
                #Other features
                Game_ID.append(data.data[a]['data'][b]['gamePk'])
                Game_Type.append(data.data[a]['data'][b]['gameData']['game']['type'])
                Event_ID.append(data.data[a]['data'][b]['liveData']['plays']['allPlays'][i]['about']['eventIdx'])
                Event_Type.append(data.data[a]['data'][b]['liveData']['plays']['allPlays'][i]['result']['event'])
                Home.append(data.data[a]['data'][b]['gameData']['teams']['home']['name'])
                Away.append(data.data[a]['data'][b]['gameData']['teams']['away']['name'])
                if data.data[a]['data'][b]['liveData']['plays']['allPlays'][i]['about']['periodType'] =='SHOOTOUT':
                    Home_Rink.append(np.nan)
                else:
                    Home_Rink.append(data.data[a]['data'][b]['liveData']['linescore']['periods'][data.data[a]['data'][b]['liveData']['plays']['allPlays'][i]['about']['period']-1]['home'].get('rinkSide', np.nan))

                if 'strength' in data.data[a]['data'][b]['liveData']['plays']['allPlays'][i]['result'].keys():
                    Power_Game.append(data.data[a]['data'][b]['liveData']['plays']['allPlays'][i]['result']['strength']['name'])
                else:
                    Power_Game.append(np.nan)

                if 'emptyNet' in data.data[a]['data'][b]['liveData']['plays']['allPlays'][i]['result'].keys():
                    Empty_Net.append(data.data[a]['data'][b]['liveData']['plays']['allPlays'][i]['result']['emptyNet'])
                else:
                    Empty_Net.append(np.nan)
                Team_Attack.append(data.data[a]['data'][b]['liveData']['plays']['allPlays'][i]['team']['name'])
                Coordinate_X.append(data.data[a]['data'][b]['liveData']['plays']['allPlays'][i]['coordinates'].get('x', np.nan))
                Coordinate_Y.append(data.data[a]['data'][b]['liveData']['plays']['allPlays'][i]['coordinates'].get('y', np.nan))
                Period.append(data.data[a]['data'][b]['liveData']['plays']['allPlays'][i]['about']['period'])
                Period_Time.append(data.data[a]['data'][b]['liveData']['plays']['allPlays'][i]['about']['periodTime'])
                Time.append(data.data[a]['data'][b]['liveData']['plays']['allPlays'][i]['about']['dateTime'])
                Shoot_type.append(data.data[a]['data'][b]['liveData']['plays']['allPlays'][i]['result'].get('secondaryType', np.nan))

                for j in range(len(data.data[a]['data'][b]['liveData']['plays']['allPlays'][i]['players'])):
                        if data.data[a]['data'][b]['liveData']['plays']['allPlays'][i]['players'][j]['playerType'] == 'Shooter':
                            Shooters.append(data.data[a]['data'][b]['liveData']['plays']['allPlays'][i]['players'][j]['player']['fullName'])
                        if data.data[a]['data'][b]['liveData']['plays']['allPlays'][i]['players'][j]['playerType'] == 'Scorer':
                            Shooters.append(data.data[a]['data'][b]['liveData']['plays']['allPlays'][i]['players'][j]['player']['fullName'])
                        if data.data[a]['data'][b]['liveData']['plays']['allPlays'][i]['players'][j]['playerType'] == 'Goalie':
                            Goalies.append(data.data[a]['data'][b]['liveData']['plays']['allPlays'][i]['players'][j]['player']['fullName'])

            if len(Goalies) < len(Game_ID):
                Goalies.append(np.nan)


data_game = {'Game_ID': Game_ID, 'Game_Type': Game_Type, 'Event_ID': Event_ID, 'Last_Event_ID': Last_Event_ID, 'Home_Team': Home, 'Home_Rink': Home_Rink, 'Away_Team': Away, 'Event_Type': Event_Type, 'Last_Event_Type': Last_Event_Type, 'Shoot_Type': Shoot_type, 'Time': Time, 'Period': Period, 'Last_Period': Last_Period, 'Period_Time': Period_Time, 'Last_Period_Time': Last_Period_Time, 'Team_Attack': Team_Attack, 'Power_Game': Power_Game, 'Empty_Net': Empty_Net, 'Shooters_scorer': Shooters, 'Goalies': Goalies, 'X_Coordinate': Coordinate_X, 'Last_Coordinate_X': Last_Coordinate_X, 'Y_Coordinate': Coordinate_Y, 'Last_Coordinate_Y': Last_Coordinate_Y}
df = pd.DataFrame(data_game)
df

,Game_ID,Game_Type,Event_ID,Last_Event_ID,Home_Team,Home_Rink,Away_Team,Event_Type,Last_Event_Type,Shoot_Type,...,Last_Period_Time,Team_Attack,Power_Game,Empty_Net,Shooters_scorer,Goalies,X_Coordinate,Last_Coordinate_X,Y_Coordinate,Last_Coordinate_Y
0,2015020364,R,5,4,Nashville Predators,left,Arizona Coyotes,Shot,Hit,Wrist Shot,...,00:30,Nashville Predators,NaN,NaN,Filip Forsberg,Mike Smith,50.0,-78.0,20.0,-38.0
1,2015020364,R,12,10,Nashville Predators,left,Arizona Coyotes,Shot,Faceoff,Wrist Shot,...,01:19,Nashville Predators,NaN,NaN,Cody Hodgson,Mike Smith,77.0,69.0,6.0,-22.0
2,2015020364,R,13,11,Nashville Predators,left,Arizona Coyotes,Shot,Takeaway,Wrist Shot,...,01:48,Nashville Predators,NaN,NaN,Craig Smith,Mike Smith,86.0,35.0,-12.0,-2.0
3,2015020364,R,18,17,Nashville Predators,left,Arizona Coyotes,Shot,Faceoff,Backhand,...,03:03,Nashville Predators,NaN,NaN,Viktor Arvidsson,Mike Smith,82.0,69.0,7.0,22.0
4,2015020364,R,32,31,Nashville Predators,left,Arizona Coyotes,Shot,Blocked Shot,Wrist Shot,...,04:46,Nashville Predators,NaN,NaN,Seth Jones,Mike Smith,48.0,85.0,-10.0,-11.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
311101,2018021002,R,285,284,Toronto Maple Leafs,right,Buffalo Sabres,Shot,Shot,Wrist Shot,...,16:37,Toronto Maple Leafs,NaN,NaN,Zach Hyman,Linus Ullmark,-47.0,75.0,13.0,0.0
311102,2018021002,R,286,285,Toronto Maple Leafs,right,Buffalo Sabres,Shot,Shot,Backhand,...,16:48,Buffalo Sabres,NaN,NaN,Jeff Skinner,Frederik Andersen,74.0,-47.0,-2.0,13.0
311103,2018021002,R,287,286,Toronto Maple Leafs,right,Buffalo Sabres,Shot,Shot,Wrist Shot,...,16:56,Buffalo Sabres,NaN,NaN,Jeff Skinner,Frederik Andersen,78.0,74.0,5.0,-2.0
311104,2018021002,R,292,291,Toronto Maple Leafs,right,Buffalo Sabres,Goal,Takeaway,Backhand,...,17:20,Toronto Maple Leafs,Even,True,Mitchell Marner,NaN,-68.0,96.0,35.0,32.0
311105,2018021002,R,296,295,Toronto Maple Leafs,right,Buffalo Sabres,Shot,Blocked Shot,Wrist Shot,...,19:06,Toronto Maple Leafs,NaN,NaN,Frederik Gauthier,Linus Ullmark,-43.0,-64.0,-12.0,14.0

#### Adding other features

In [14]:
def calculate_seconds(my_string):
    """
    Helper function to calculate  total number of seconds represented by a string in format
    mm:ss.
    """
    separated_time = my_string.split(":")
    return int(separated_time[0])*60+int(separated_time[1])

In [6]:
# Convert Period times to number of seconds
df['Period_Time_Seconds'] = df.Period_Time.map(calculate_seconds)
df['Last_Period_Time_Seconds'] = df.Last_Period_Time.map(calculate_seconds)
df['Time_Between_Events']= df['Period_Time_Seconds']-df['Last_Period_Time_Seconds']

In [15]:
def transform_X(row):
    '''
    Given a row of the original data frame, this function transforms the coordinate X depending on the position of
    the teams in the rink. Since at the end the data is presented in a half-rink (we arbitrarily choose that
    this is the right half of the rink), when the attacking team plays on the right side of the rink , i.e
    the opponent's goal is on the left side, we need to flip the x coordinate.
    '''
    if str(row['Home_Rink']) == 'nan': #In case the rinkside information is not available, we assume the shot
        #is taken from the side that is the closest to the opponent's goal.
        return np.absolute(row['X_Coordinate'])

    else: #Otherwise we use rinkside information to determine whether to flip X coordinate as described above.
        if row['Home_Team'] == row['Team_Attack']:
            if row['Home_Rink'] == 'right':
                return -(row['X_Coordinate'])
            else:
                return row['X_Coordinate']
        else:
            if row['Home_Rink'] == 'left':
                return -(row['X_Coordinate'])
            else:
                return row['X_Coordinate']

In [8]:
# Transform X coordinates to one side of the rink
df['X_Transformed'] = df.apply(transform_X, axis=1)

In [16]:
def transform_last_X(row):
    '''
    Given a row of the original data frame, this function transforms the Last coordinate X depending on the position of
    the teams in the rink. Since we aim to present the data in a half-rink (we arbitrarily choose that
    this is the right half of the rink), when the attacking team plays on the right side of the rink , i.e
    the opponent's goal is on the left side, we need to flip the x coordinate.
    '''
    if str(row['Home_Rink']) == 'nan': #In case the rinkside information is not available, we assume the shot
        #is taken from the side that is the closest to the opponent's goal.
        return np.absolute(row['Last_Coordinate_X'])

    else: #Otherwise we use rinkside information to determine whether to flip X coordinate as described above.
        if row['Home_Team'] == row['Team_Attack']:
            if row['Home_Rink'] == 'right':
                return -(row['Last_Coordinate_X'])
            else:
                return row['Last_Coordinate_X']
        else:
            if row['Home_Rink'] == 'left':
                return -(row['Last_Coordinate_X'])
            else:
                return row['Last_Coordinate_X']

In [10]:
# Transform Last Coordinates X to one side of the rink
df['Last_X_Transformed'] = df.apply(transform_last_X, axis=1)

In [17]:
def get_distance(row):
    ''' Given a row of the original dataframe, this function computes the distance between one event and its preceding event'''
    return ((row['X_Coordinate']-row['Last_Coordinate_X'])**2+(row['Y_Coordinate']-row['Last_Coordinate_Y'])**2)**(1/2)

In [12]:
# Get the distance between all pairs of events and preceding events
df['Distance_Last_Event']= df.apply(get_distance, axis=1)

In [18]:
def get_distance_net(row):
    '''
    Given a row of the original dataframe, this function computes the distance between the shot and the net
    '''
    return ((89- row['X_Transformed'])**2+(0-row['Y_Coordinate'])**2)**(1/2)
# Add distance to net
df['Distance_Net']=df.apply(get_distance_net, axis=1)

In [14]:
# Creat a boolean column testing whether the last event type was a shot
df['Rebond'] = df['Last_Event_Type'] == 'Shot'

In [19]:
def get_angle(row):
    '''
    Given a row on the original dataframe, this function computes the angle of the shot. It first tests whether the last event was a Rebond. If false, it returns NAN. If true, it then tests whether the X_Transformed coordinate of the event is 89 (the x coordinate of the net). If also true, it returns an angle of either -90 or 90 degrees depending on its y coordinate. If false, it computes the angle according to the right triangle properties.
    '''
    if row['X_Transformed'] ==89:
        return 90*row['Y_Coordinate']/(np.abs(row['Y_Coordinate']))
    else :
        return np.arctan((row['Y_Coordinate']/(89-row['X_Transformed'])))*180/math.pi

In [16]:
#Set the angles of the events
df['Angle'] = df.apply(get_angle, axis = 1)

/var/folders/yp/s64kzpxd3k95zytpqbx3y1tw0000gn/T/ipykernel_20622/4246329903.py:6: RuntimeWarning: invalid value encountered in double_scalars
  return 90*row['Y_Coordinate']/(np.abs(row['Y_Coordinate']))

In [20]:
def get_last_angle(row):
    '''
    Given a row on the original dataframe, this function computes the angle of the last shot. It first tests whether the last event was a Rebond. If false, it returns NAN. If true, it then tests whether the Last_X_Transformed coordinate of the event is 89 (the x coordinate of the net). If also true, it returns an angle of either -90 or 90 degrees depending on the last event's y coordinate. If false, it computes the angle of the last shot according to the right triangle properties.
    '''
    if row['Rebond']:
        if row['Last_X_Transformed'] ==89:
            return 90*row['Last_Coordinate_Y']/(np.abs(row['Last_Coordinate_Y']))
        else :
            return np.arctan((row['Last_Coordinate_Y']/(89-row['Last_X_Transformed'])))*180/math.pi
    else:
        return 0.0

In [18]:
# Set a column for the angles of the last events that were shots
df['Last_Angle'] = df.apply(get_last_angle, axis = 1)

In [19]:
# Compute the angular difference between the angle of the present event and the angle of the last events (both shots).
df['Delta_Angle'] = df['Angle']-df['Last_Angle']

In [20]:
# Compute the speed between an event and a last event
df['Speed'] = df['Distance_Last_Event']/df['Time_Between_Events']

In [21]:
df

,Game_ID,Game_Type,Event_ID,Last_Event_ID,Home_Team,Home_Rink,Away_Team,Event_Type,Last_Event_Type,Shoot_Type,...,Time_Between_Events,X_Transformed,Last_X_Transformed,Distance_Last_Event,Distance_Net,Rebond,Angle,Last_Angle,Delta_Angle,Speed
0,2015020364,R,5,4,Nashville Predators,left,Arizona Coyotes,Shot,Hit,Wrist Shot,...,6,50.0,-78.0,140.527577,43.829214,False,27.149682,0.000000,27.149682,23.421263
1,2015020364,R,12,10,Nashville Predators,left,Arizona Coyotes,Shot,Faceoff,Wrist Shot,...,29,77.0,69.0,29.120440,13.416408,False,26.565051,0.000000,26.565051,1.004153
2,2015020364,R,13,11,Nashville Predators,left,Arizona Coyotes,Shot,Takeaway,Wrist Shot,...,7,86.0,35.0,51.971146,12.369317,False,-75.963757,0.000000,-75.963757,7.424449
3,2015020364,R,18,17,Nashville Predators,left,Arizona Coyotes,Shot,Faceoff,Backhand,...,10,82.0,69.0,19.849433,9.899495,False,45.000000,0.000000,45.000000,1.984943
4,2015020364,R,32,31,Nashville Predators,left,Arizona Coyotes,Shot,Blocked Shot,Wrist Shot,...,23,48.0,85.0,37.013511,42.201896,False,-13.706961,0.000000,-13.706961,1.609283
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
311101,2018021002,R,285,284,Toronto Maple Leafs,right,Buffalo Sabres,Shot,Shot,Wrist Shot,...,11,47.0,-75.0,122.690668,43.965896,True,17.198541,0.000000,17.198541,11.153697
311102,2018021002,R,286,285,Toronto Maple Leafs,right,Buffalo Sabres,Shot,Shot,Backhand,...,8,74.0,-47.0,121.926207,15.132746,True,-7.594643,5.460213,-13.054856,15.240776
311103,2018021002,R,287,286,Toronto Maple Leafs,right,Buffalo Sabres,Shot,Shot,Wrist Shot,...,2,78.0,74.0,8.062258,12.083046,True,24.443955,-7.594643,32.038598,4.031129
311104,2018021002,R,292,291,Toronto Maple Leafs,right,Buffalo Sabres,Goal,Takeaway,Backhand,...,43,68.0,-96.0,164.027437,40.816663,False,59.036243,0.000000,59.036243,3.814592
311105,2018021002,R,296,295,Toronto Maple Leafs,right,Buffalo Sabres,Shot,Blocked Shot,Wrist Shot,...,5,43.0,64.0,33.421550,47.539457,False,-14.620874,0.000000,-14.620874,6.684310

In [22]:
df.columns

Index(['Game_ID', 'Game_Type', 'Event_ID', 'Last_Event_ID', 'Home_Team',
       'Home_Rink', 'Away_Team', 'Event_Type', 'Last_Event_Type', 'Shoot_Type',
       'Time', 'Period', 'Last_Period', 'Period_Time', 'Last_Period_Time',
       'Team_Attack', 'Power_Game', 'Empty_Net', 'Shooters_scorer', 'Goalies',
       'X_Coordinate', 'Last_Coordinate_X', 'Y_Coordinate',
       'Last_Coordinate_Y', 'Period_Time_Seconds', 'Last_Period_Time_Seconds',
       'Time_Between_Events', 'X_Transformed', 'Last_X_Transformed',
       'Distance_Last_Event', 'Distance_Net', 'Rebond', 'Angle', 'Last_Angle',
       'Delta_Angle', 'Speed'],
      dtype='object')

#### Bonus part: Powerplay information

Here we are going to go back to raw data because we need more features from there to calculate the three penalty target features. The new features we added to our data frame in this notebook will be discarded here. Then both sets of features will be combined into one data frame, the corresponding code can be found in util/engineered_data_frame.py, which is just the combination of code from the first part of this notebook and from this part. At the end of the notebook an import of the full data set is made to showcase the final result.

In [8]:
def reset_penalty_stack():
    """
    Will be called on each period start to reset the penalty_stack to empty state.
    """
    penalty_stack = { #Dictionary contaning current penalty information. Will be updated in each event.
        "home": [], #List of current active penalites for the home team
        "away": [], #Same for away team. Format of penalty tuple: (playerID, penaltyMinutes, penaltySeverity, periodTime)
        "team_on_power_play": "none", #Current team that is on power play, can be "home", "away" or "none"
        "power_play_since": 0, #Period time of the start of the current powerplay, in seconds
    }
    return penalty_stack
#Penalty types compared from least severe to most severe
RANKED_PENALTIES = ["Minor", "Double Minor", "Major", "Misconduct", "Game Misconduct", "Match"]

In [9]:
def penalty_stack_update_on_any_event(penalty_stack,period_time):
    """
    Update function, will be the first one to be called on any event.
    Updates penalty_stack by deleting penalties which time is over.
    A penalty is represented as a tuple (player_id, penalty_minutes, penalty_severity, period_time).
    """
    #Preprocessing
    period_time = calculate_seconds(period_time)

    #Delete outdated penalties
    for team in ["home", "away"]:
        penalties_to_delete = []
        for i,penalty  in enumerate(penalty_stack[team]):
            penalty_duration = penalty[1]*60
            penalty_start = penalty[3]
            penalty_severity = penalty[2]
            if penalty_start+penalty_duration <= period_time:
                penalties_to_delete.append(penalty)
            elif penalty_severity == "Double Minor":
                #Double minors which have less than 2 mins left on the clock become minor penalties
                if period_time-penalty_start> 2*60:
                    new_minor_penalty = (penalty[0],2,"Minor", penalty_start+2*60)
                    penalty_stack[team][i]=new_minor_penalty
        for penalty in penalties_to_delete: #actually removing the penalties
            penalty_stack[team].remove(penalty)


    old_team_on_power_play = penalty_stack["team_on_power_play"]
    #Determining who's in powerplay now
    if len(penalty_stack["home"]) > len(penalty_stack["away"]): #In this case away is on powerplay
        penalty_stack["team_on_power_play"] = "away"
    elif len(penalty_stack["home"]) < len(penalty_stack["away"]):
        penalty_stack["team_on_power_play"] = "home"
    else:
        penalty_stack["team_on_power_play"] = "none"

    #Now if the team on power play changed, we set "power_play_since" to be perod_time, else we do nothing,
    #Thus preserving the start time of the already existing power_play
    if old_team_on_power_play != penalty_stack["team_on_power_play"]:
        if penalty_stack["team_on_power_play"] == "none":
            #Makes more sense to reset "power_play_since" to zero here, although can be set
            #to anything we want.
            penalty_stack["power_play_since"] = 0
        else :
            penalty_stack["power_play_since"] =  period_time

    return penalty_stack

In [10]:
def penalty_stack_update_on_penalty_event(penalty_stack, penalty_severity, penalty_minutes, period_time, player_id, team, home):
    """
    Update function to be called on each penalty event. Updates the penalty_stack.
    """
    #Pre-processing
    concerned_team = "home" if team==home else "away"

    if penalty_severity in ["Minor", "Bench Minor"]:
        if penalty_minutes==4:
            penalty_severity="Double Minor" #Creating Double Minor Severity for convenience.
        else:
            penalty_severity="Minor" #Bench Minor Penalties have same effect on the team as minor.
    if penalty_severity=="Match":
        penalty_minutes=5 #Match penalties are registered for 10 mins for statistical
        #Purposes but the team stays shorthanded for 5 minutes only. (Piazza question @95)

    period_time = calculate_seconds(period_time)

    if player_id in [penalty[0] for penalty in penalty_stack[concerned_team]] and penalty_severity!="Penalty Shot":
        #If player already has a penalty
        #Apply the most severe one (Piazza question @96)
        index_of_players_penalty = [penalty[0] for penalty in penalty_stack[concerned_team]].index(player_id)
        if RANKED_PENALTIES.index(penalty_severity) > RANKED_PENALTIES.index(penalty_stack[concerned_team][index_of_players_penalty][2]):
            if penalty_severity in ["Misconduct", "Game Misconduct"]:
                #Those penalties are more severe but the team doesn't stay shorthanded with them.
                #Since those penalties override the already announced one, we could simply delete the latter
                penalty_stack[concerned_team].pop(index_of_players_penalty)
            else:
                penalty_stack[concerned_team].pop(index_of_players_penalty)
                penalty_stack[concerned_team].append((player_id, penalty_minutes, penalty_severity, period_time))


    else: #Treat this as a penalty for a new player
        if penalty_severity in ["Misconduct", "Game Misconduct", "Penalty Shot"]:
            return penalty_stack #Only penalties of type "Minor", "Bench Minor", "Major", and "Match" can make a team
        #Short-handed. Other types of penalties exclude a particular player but allows the team to replace him
        #With someone else. Penalty shots constitute no exclusions.

        #Adding penalty to the concerned team.
        #If already 2 penalties exist, ignore the new penalty
        if len(penalty_stack[concerned_team])<2:
            penalty_stack[concerned_team].append((player_id, penalty_minutes, penalty_severity, period_time))

    old_team_on_power_play = penalty_stack["team_on_power_play"]
    #Determining who's in powerplay now
    if len(penalty_stack["home"]) > len(penalty_stack["away"]): #In this case away is on powerplay
        penalty_stack["team_on_power_play"] = "away"
    elif len(penalty_stack["home"]) < len(penalty_stack["away"]):
        penalty_stack["team_on_power_play"] = "home"
    else:
        penalty_stack["team_on_power_play"] = "none"

    #Now if the team on power play changed, we set "power_play_since" to be perod_time, else we do nothing,
    #Thus preserving the start time of the already existing power_play
    if old_team_on_power_play != penalty_stack["team_on_power_play"]:
        if penalty_stack["team_on_power_play"] == "none":
            #Makes more sense to reset "power_play_since" to zero here, although can be set
            #to anything we want.
            penalty_stack["power_play_since"] = 0
        else :
            penalty_stack["power_play_since"] =  period_time

    return penalty_stack

In [11]:
def penalty_stack_update_on_goal_event(penalty_stack, period_time, scoring_team, home):
    """
    Update function to be called each goal event.
    """
    #Pre-processing
    conceding_team = "away" if scoring_team==home else "home"
    scoring_team = "away" if conceding_team=="home" else "away"
    period_time = calculate_seconds(period_time)
    #If the conceding_team is short-handed, delete the minor penalty corresponding
    #to the least amount of time on the clock (Double minors with t>2 mins become minors)
    if len(penalty_stack[conceding_team]) > len(penalty_stack[scoring_team]):
        #Now create a list of minor penalties or double minors with time >2 mins
        #Here double minors with time <=2 mins have been automatically transformed to minors in previous
        #update calls.
        candidate_penalties_idxs = [i for i in range(len(penalty_stack[conceding_team])) if
                                    penalty_stack[conceding_team][i][2] in ["Minor", "Double Minor"]]
        if len(candidate_penalties_idxs) == 0:
            return penalty_stack #No Minor or Double Minor penalties to be stopped
        else:
            #Look for the penalty with the shortest time on clock (for double minor consider
            #duration = 2)
            shortest_penalty_index = candidate_penalties_idxs[0]
            shortest_penalty_time_on_clock = 2*60-\
                                             (period_time-penalty_stack[conceding_team][shortest_penalty_index][3])
            for idx in candidate_penalties_idxs:
                time_on_clock = 2*60-\
                                             (period_time-penalty_stack[conceding_team][idx][3])
                if time_on_clock<shortest_penalty_time_on_clock:
                    time_on_clock = shortest_penalty_time_on_clock
                    shortest_penalty_index = idx

            if penalty_stack[conceding_team][shortest_penalty_index][2]=="Double Minor":
                #Double Minor is replaced by a minor
                double_minor_penalty = penalty_stack[conceding_team].pop(shortest_penalty_index)
                new_minor_penalty = (double_minor_penalty[0],2,"Minor", period_time)
                penalty_stack[conceding_team].append(new_minor_penalty)
            else:
                #Just delete the minor penalty
                penalty_stack[conceding_team].pop(shortest_penalty_index)

        old_team_on_power_play = penalty_stack["team_on_power_play"]
        #Determining who's in powerplay now
        if len(penalty_stack["home"]) > len(penalty_stack["away"]): #In this case away is on powerplay
            penalty_stack["team_on_power_play"] = "away"
        elif len(penalty_stack["home"]) < len(penalty_stack["away"]):
            penalty_stack["team_on_power_play"] = "home"
        else:
            penalty_stack["team_on_power_play"] = "none"

        #Now if the team on power play changed, we set "power_play_since" to be perod_time, else we do nothing,
        #Thus preserving the start time of the already existing power_play
        if old_team_on_power_play != penalty_stack["team_on_power_play"]:
            if penalty_stack["team_on_power_play"] == "none":
                #Makes more sense to reset "power_play_since" to zero here, although can be set
                #to anything we want.
                penalty_stack["power_play_since"] = 0
            else :
                penalty_stack["power_play_since"] =  period_time




    return penalty_stack

In [21]:
Empty_Net = []
Game_ID = []
Game_Type = []
Event_ID = []
Event_Type = []
Power_Game = []
Team_Attack = []
Coordinate_X = []
Coordinate_Y = []
Period = []
Period_Time = []
Time = []
Shooters = []
Scorers = []
Goalies = []
Shoot_type = []
Home = []
Away = []
Home_Rink = []
#Last Event Features
Last_Event_ID = []
Last_Event_Type = []
Last_Coordinate_X = []
Last_Coordinate_Y = []
Last_Period = []
Last_Period_Time = []
Last_Time = []
Powerplay_Since = []
Friendly_Non_Goalies = []
Opponent_Non_Goalies = []

penalty_stack = reset_penalty_stack()
for a in range(len(data.data)):
    for b in range(len(data.data[a]['data'])):
        for i in range(len(data.data[a]['data'][b]['liveData']['plays']['allPlays'])):
            if data.data[a]['data'][b]['liveData']['plays']['allPlays'][i]['result']['event'] == 'Period Start':
                penalty_stack = reset_penalty_stack()
            #Make the on any event update to delete outdated penalties
            penalty_stack = penalty_stack_update_on_any_event(
                penalty_stack,
                data.data[a]['data'][b]['liveData']['plays']['allPlays'][i]['about']['periodTime']
            )
            if data.data[a]['data'][b]['liveData']['plays']['allPlays'][i]['result']['event'] == 'Shot' or data.data[a]['data'][b]['liveData']['plays']['allPlays'][i]['result']['event'] == 'Goal':
                #Features corresponding to last event
                Last_Event_ID.append(data.data[a]['data'][b]['liveData']['plays']['allPlays'][i-1]['about']['eventIdx'])
                Last_Event_Type.append(data.data[a]['data'][b]['liveData']['plays']['allPlays'][i-1]['result']['event'])
                Last_Coordinate_X.append(data.data[a]['data'][b]['liveData']['plays']['allPlays'][i-1]['coordinates'].get('x', np.nan))
                Last_Coordinate_Y.append(data.data[a]['data'][b]['liveData']['plays']['allPlays'][i-1]['coordinates'].get('y', np.nan))
                Last_Period.append(data.data[a]['data'][b]['liveData']['plays']['allPlays'][i-1]['about']['period'])
                Last_Period_Time.append(data.data[a]['data'][b]['liveData']['plays']['allPlays'][i-1]['about']['periodTime'])
                Last_Time.append(data.data[a]['data'][b]['liveData']['plays']['allPlays'][i-1]['about']['dateTime'])
                #Features corresponding to current event
                Game_ID.append(data.data[a]['data'][b]['gamePk'])
                Game_Type.append(data.data[a]['data'][b]['gameData']['game']['type'])
                Event_ID.append(data.data[a]['data'][b]['liveData']['plays']['allPlays'][i]['about']['eventIdx'])
                Event_Type.append(data.data[a]['data'][b]['liveData']['plays']['allPlays'][i]['result']['event'])
                Home.append(data.data[a]['data'][b]['gameData']['teams']['home']['name'])
                Away.append(data.data[a]['data'][b]['gameData']['teams']['away']['name'])
                if data.data[a]['data'][b]['liveData']['plays']['allPlays'][i]['about']['periodType'] =='SHOOTOUT':
                    Home_Rink.append(np.nan)
                else:
                    Home_Rink.append(data.data[a]['data'][b]['liveData']['linescore']['periods'][data.data[a]['data'][b]['liveData']['plays']['allPlays'][i]['about']['period']-1]['home'].get('rinkSide', np.nan))

                if 'strength' in data.data[a]['data'][b]['liveData']['plays']['allPlays'][i]['result'].keys():
                    Power_Game.append(data.data[a]['data'][b]['liveData']['plays']['allPlays'][i]['result']['strength']['name'])
                else:
                    Power_Game.append(np.nan)

                if 'emptyNet' in data.data[a]['data'][b]['liveData']['plays']['allPlays'][i]['result'].keys():
                    Empty_Net.append(data.data[a]['data'][b]['liveData']['plays']['allPlays'][i]['result']['emptyNet'])
                else:
                    Empty_Net.append(np.nan)
                Team_Attack.append(data.data[a]['data'][b]['liveData']['plays']['allPlays'][i]['team']['name'])
                Coordinate_X.append(data.data[a]['data'][b]['liveData']['plays']['allPlays'][i]['coordinates'].get('x', np.nan))
                Coordinate_Y.append(data.data[a]['data'][b]['liveData']['plays']['allPlays'][i]['coordinates'].get('y', np.nan))
                Period.append(data.data[a]['data'][b]['liveData']['plays']['allPlays'][i]['about']['period'])
                Period_Time.append(data.data[a]['data'][b]['liveData']['plays']['allPlays'][i]['about']['periodTime'])
                Time.append(data.data[a]['data'][b]['liveData']['plays']['allPlays'][i]['about']['dateTime'])
                Shoot_type.append(data.data[a]['data'][b]['liveData']['plays']['allPlays'][i]['result'].get('secondaryType', np.nan))

                for j in range(len(data.data[a]['data'][b]['liveData']['plays']['allPlays'][i]['players'])):
                        if data.data[a]['data'][b]['liveData']['plays']['allPlays'][i]['players'][j]['playerType'] == 'Shooter':
                            Shooters.append(data.data[a]['data'][b]['liveData']['plays']['allPlays'][i]['players'][j]['player']['fullName'])
                        if data.data[a]['data'][b]['liveData']['plays']['allPlays'][i]['players'][j]['playerType'] == 'Scorer':
                            Shooters.append(data.data[a]['data'][b]['liveData']['plays']['allPlays'][i]['players'][j]['player']['fullName'])
                        if data.data[a]['data'][b]['liveData']['plays']['allPlays'][i]['players'][j]['playerType'] == 'Goalie':
                            Goalies.append(data.data[a]['data'][b]['liveData']['plays']['allPlays'][i]['players'][j]['player']['fullName'])

                #Add data related to penalties
                period_time = Period_Time[-1]
                period_time = calculate_seconds(period_time)
                if penalty_stack["power_play_since"]== 0:
                    Powerplay_Since.append(0)
                else:
                    Powerplay_Since.append(period_time-penalty_stack["power_play_since"])
                team_attack_is = "home" if Team_Attack[-1]==Home[-1] else "away"
                team_opponent_is = "home" if team_attack_is=="away" else "away"
                Friendly_Non_Goalies.append(5-len(penalty_stack[team_attack_is]))
                Opponent_Non_Goalies.append(5-len(penalty_stack[team_opponent_is]))
                #Now, if the shot was actually a goal, update the penalt_stack according
                #To the rule of deleting a minor penalty when opponent scores
                if Event_Type[-1]=='Goal':
                    penalty_stack = penalty_stack_update_on_goal_event(
                        penalty_stack,
                        Period_Time[-1],
                        Team_Attack[-1],
                        Home[-1]
                    )
            elif data.data[a]['data'][b]['liveData']['plays']['allPlays'][i]['result']['event'] == 'Penalty':
                penalty_stack = penalty_stack_update_on_penalty_event(
                    penalty_stack,
                    data.data[a]['data'][b]['liveData']['plays']['allPlays'][i]['result']['penaltySeverity'],
                    data.data[a]['data'][b]['liveData']['plays']['allPlays'][i]['result']['penaltyMinutes'],
                    data.data[a]['data'][b]['liveData']['plays']['allPlays'][i]['about']['periodTime'],
                    data.data[a]['data'][b]['liveData']['plays']['allPlays'][i]['players'][0]['player']['id'],
                    data.data[a]['data'][b]['liveData']['plays']['allPlays'][i]['team']['name'],
                    data.data[a]['data'][b]['gameData']['teams']['home']['name'])

            if len(Goalies) < len(Game_ID):
                Goalies.append(np.nan)


data_game = {'Game_ID': Game_ID, 'Game_Type': Game_Type, 'Event_ID': Event_ID, 'Last_Event_ID': Last_Event_ID,
             'Home_Team': Home, 'Home_Rink': Home_Rink, 'Away_Team': Away, 'Event_Type': Event_Type,
             'Last_Event_Type': Last_Event_Type, 'Shoot_Type': Shoot_type, 'Time': Time, 'Period': Period,
             'Last_Period': Last_Period, 'Period_Time': Period_Time, 'Last_Period_Time': Last_Period_Time,
             'Team_Attack': Team_Attack, 'Power_Game': Power_Game, 'Empty_Net': Empty_Net,
             'Shooters_scorer': Shooters, 'Goalies': Goalies, 'X_Coordinate': Coordinate_X,
             'Last_Coordinate_X': Last_Coordinate_X, 'Y_Coordinate': Coordinate_Y,
             'Last_Coordinate_Y': Last_Coordinate_Y, 'Powerplay_Since': Powerplay_Since,
             'Friendly_Non_Goalies': Friendly_Non_Goalies, 'Opponent_Non_Goalies': Opponent_Non_Goalies}
df = pd.DataFrame(data_game)

In [22]:
df

,Game_ID,Game_Type,Event_ID,Last_Event_ID,Home_Team,Home_Rink,Away_Team,Event_Type,Last_Event_Type,Shoot_Type,...,Empty_Net,Shooters_scorer,Goalies,X_Coordinate,Last_Coordinate_X,Y_Coordinate,Last_Coordinate_Y,Powerplay_Since,Friendly_Non_Goalies,Opponent_Non_Goalies
0,2015020364,R,5,4,Nashville Predators,left,Arizona Coyotes,Shot,Hit,Wrist Shot,...,NaN,Filip Forsberg,Mike Smith,50.0,-78.0,20.0,-38.0,0,5,5
1,2015020364,R,12,10,Nashville Predators,left,Arizona Coyotes,Shot,Faceoff,Wrist Shot,...,NaN,Cody Hodgson,Mike Smith,77.0,69.0,6.0,-22.0,0,5,5
2,2015020364,R,13,11,Nashville Predators,left,Arizona Coyotes,Shot,Takeaway,Wrist Shot,...,NaN,Craig Smith,Mike Smith,86.0,35.0,-12.0,-2.0,0,5,5
3,2015020364,R,18,17,Nashville Predators,left,Arizona Coyotes,Shot,Faceoff,Backhand,...,NaN,Viktor Arvidsson,Mike Smith,82.0,69.0,7.0,22.0,0,5,5
4,2015020364,R,32,31,Nashville Predators,left,Arizona Coyotes,Shot,Blocked Shot,Wrist Shot,...,NaN,Seth Jones,Mike Smith,48.0,85.0,-10.0,-11.0,0,5,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
311101,2018021002,R,285,284,Toronto Maple Leafs,right,Buffalo Sabres,Shot,Shot,Wrist Shot,...,NaN,Zach Hyman,Linus Ullmark,-47.0,75.0,13.0,0.0,0,5,5
311102,2018021002,R,286,285,Toronto Maple Leafs,right,Buffalo Sabres,Shot,Shot,Backhand,...,NaN,Jeff Skinner,Frederik Andersen,74.0,-47.0,-2.0,13.0,0,5,5
311103,2018021002,R,287,286,Toronto Maple Leafs,right,Buffalo Sabres,Shot,Shot,Wrist Shot,...,NaN,Jeff Skinner,Frederik Andersen,78.0,74.0,5.0,-2.0,0,5,5
311104,2018021002,R,292,291,Toronto Maple Leafs,right,Buffalo Sabres,Goal,Takeaway,Backhand,...,True,Mitchell Marner,NaN,-68.0,96.0,35.0,32.0,0,5,5
311105,2018021002,R,296,295,Toronto Maple Leafs,right,Buffalo Sabres,Shot,Blocked Shot,Wrist Shot,...,NaN,Frederik Gauthier,Linus Ullmark,-43.0,-64.0,-12.0,14.0,0,5,5

In [23]:
df.columns

Index(['Game_ID', 'Game_Type', 'Event_ID', 'Last_Event_ID', 'Home_Team',
       'Home_Rink', 'Away_Team', 'Event_Type', 'Last_Event_Type', 'Shoot_Type',
       'Time', 'Period', 'Last_Period', 'Period_Time', 'Last_Period_Time',
       'Team_Attack', 'Power_Game', 'Empty_Net', 'Shooters_scorer', 'Goalies',
       'X_Coordinate', 'Last_Coordinate_X', 'Y_Coordinate',
       'Last_Coordinate_Y', 'Powerplay_Since', 'Friendly_Non_Goalies',
       'Opponent_Non_Goalies'],
      dtype='object')

In [24]:
df.Opponent_Non_Goalies.value_counts()

5    260187
4     48123
3      2796
Name: Opponent_Non_Goalies, dtype: int64

In [25]:
df.Friendly_Non_Goalies.value_counts()

5    293175
4     17237
3       694
Name: Friendly_Non_Goalies, dtype: int64

In [26]:
df["Powerplay_Since"].value_counts()

0      260107
8         661
7         579
10        568
6         559
        ...
261         1
247         1
240         1
426         1
257         1
Name: Powerplay_Since, Length: 304, dtype: int64

In [27]:
df_goal = df[(df.Event_Type=="Goal") ]

In [28]:
df_goal.Power_Game.value_counts()

Even            22509
Power Play       5860
Short Handed      818
Name: Power_Game, dtype: int64

In [29]:
df_goal[(df_goal.Power_Game=="Even") & (df_goal.Opponent_Non_Goalies !=df_goal.Friendly_Non_Goalies)]

,Game_ID,Game_Type,Event_ID,Last_Event_ID,Home_Team,Home_Rink,Away_Team,Event_Type,Last_Event_Type,Shoot_Type,...,Empty_Net,Shooters_scorer,Goalies,X_Coordinate,Last_Coordinate_X,Y_Coordinate,Last_Coordinate_Y,Powerplay_Since,Friendly_Non_Goalies,Opponent_Non_Goalies
260,2015020221,R,112,111,Tampa Bay Lightning,right,Buffalo Sabres,Goal,Giveaway,Wrist Shot,...,False,Cody Franson,Andrei Vasilevskiy,50.0,14.0,-22.0,-32.0,74,4,5
2307,2015020020,R,40,39,Florida Panthers,right,Philadelphia Flyers,Goal,Giveaway,Tip-In,...,False,Jussi Jokinen,Steve Mason,-80.0,-97.0,-7.0,8.0,129,5,4
3294,2015021220,R,97,96,Montréal Canadiens,right,Tampa Bay Lightning,Goal,Missed Shot,Backhand,...,False,Tomas Plekanec,Andrei Vasilevskiy,-82.0,-72.0,4.0,-40.0,34,5,4
4437,2015021129,R,48,47,Carolina Hurricanes,right,New Jersey Devils,Goal,Faceoff,Snap Shot,...,False,Ron Hainsey,Scott Wedgewood,-75.0,-69.0,-5.0,-22.0,19,4,3
8315,2015020201,R,211,210,Los Angeles Kings,left,Florida Panthers,Goal,Shot,Backhand,...,False,Anze Kopitar,Roberto Luongo,83.0,82.0,7.0,4.0,68,5,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
306247,2018020900,R,101,100,Chicago Blackhawks,right,Columbus Blue Jackets,Goal,Missed Shot,Wrist Shot,...,False,Artemi Panarin,Cam Ward,72.0,69.0,6.0,1.0,88,4,5
306309,2018021242,R,53,52,Buffalo Sabres,left,Ottawa Senators,Goal,Shot,Backhand,...,False,Jean-Gabriel Pageau,Carter Hutton,-80.0,-49.0,-6.0,-31.0,68,4,5
307131,2018020150,R,192,191,Nashville Predators,right,Edmonton Oilers,Goal,Faceoff,Backhand,...,False,Connor McDavid,Juuse Saros,85.0,0.0,-7.0,0.0,79,4,5
307372,2018020629,R,92,91,Pittsburgh Penguins,left,Winnipeg Jets,Goal,Hit,Tip-In,...,False,Matt Cullen,Connor Hellebuyck,78.0,3.0,-3.0,-40.0,115,5,4
307872,2018021203,R,71,70,Carolina Hurricanes,right,Philadelphia Flyers,Goal,Shot,Snap Shot,...,False,Dougie Hamilton,Cam Talbot,-74.0,-80.0,4.0,-4.0,91,5,4

In [30]:
df_goal[(df_goal.Power_Game=="Power Play") & (df_goal.Opponent_Non_Goalies >=df_goal.Friendly_Non_Goalies)]

,Game_ID,Game_Type,Event_ID,Last_Event_ID,Home_Team,Home_Rink,Away_Team,Event_Type,Last_Event_Type,Shoot_Type,...,Empty_Net,Shooters_scorer,Goalies,X_Coordinate,Last_Coordinate_X,Y_Coordinate,Last_Coordinate_Y,Powerplay_Since,Friendly_Non_Goalies,Opponent_Non_Goalies
158,2015021125,R,189,188,Nashville Predators,right,Columbus Blue Jackets,Goal,Hit,Slap Shot,...,False,Shea Weber,Joonas Korpisalo,-49.0,-39.0,-13.0,-36.0,0,4,4
986,2015020919,R,207,206,Anaheim Ducks,left,Edmonton Oilers,Goal,Faceoff,Wrist Shot,...,False,Ryan Getzlaf,Cam Talbot,80.0,20.0,6.0,-22.0,0,5,5
3196,2015020348,R,186,185,Nashville Predators,right,Buffalo Sabres,Goal,Missed Shot,Tip-In,...,False,Jamie McGinn,Juuse Saros,82.0,81.0,3.0,5.0,0,5,5
3197,2015020348,R,193,192,Nashville Predators,right,Buffalo Sabres,Goal,Takeaway,Snap Shot,...,False,Sam Reinhart,Juuse Saros,61.0,51.0,1.0,-38.0,0,5,5
3492,2015020124,R,289,288,Boston Bruins,left,Arizona Coyotes,Goal,Shot,Wrist Shot,...,False,Brad Marchand,Mike Smith,51.0,59.0,-12.0,-23.0,0,5,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
305714,2018020812,R,224,223,New Jersey Devils,left,Los Angeles Kings,Goal,Shot,Slap Shot,...,False,Tyler Toffoli,Keith Kinkaid,-51.0,-45.0,9.0,5.0,0,5,5
307235,2018020279,R,79,78,Pittsburgh Penguins,left,Tampa Bay Lightning,Goal,Blocked Shot,Snap Shot,...,False,Phil Kessel,Louis Domingue,64.0,77.0,0.0,1.0,0,3,3
307244,2018020279,R,127,126,Pittsburgh Penguins,right,Tampa Bay Lightning,Goal,Missed Shot,Snap Shot,...,False,Brayden Point,Matt Murray,81.0,57.0,15.0,18.0,0,5,5
307246,2018020279,R,131,130,Pittsburgh Penguins,right,Tampa Bay Lightning,Goal,Shot,Snap Shot,...,False,Brayden Point,Matt Murray,75.0,58.0,-3.0,20.0,0,5,5
307688,2018020042,R,194,193,Ottawa Senators,right,Philadelphia Flyers,Goal,Shot,Wrist Shot,...,False,Maxime Lajoie,Calvin Pickard,-72.0,-86.0,-9.0,7.0,0,4,4

In [31]:
(df_goal[(df_goal.Power_Game=="Short Handed") & (df_goal.Opponent_Non_Goalies <=df_goal.Friendly_Non_Goalies)])#.loc[283748]

,Game_ID,Game_Type,Event_ID,Last_Event_ID,Home_Team,Home_Rink,Away_Team,Event_Type,Last_Event_Type,Shoot_Type,...,Empty_Net,Shooters_scorer,Goalies,X_Coordinate,Last_Coordinate_X,Y_Coordinate,Last_Coordinate_Y,Powerplay_Since,Friendly_Non_Goalies,Opponent_Non_Goalies
2028,2015021148,R,139,138,Vancouver Canucks,left,San Jose Sharks,Goal,Faceoff,Wrist Shot,...,False,Chris Higgins,James Reimer,63.0,-69.0,18.0,22.0,0,5,5
3540,2015020574,R,189,188,Pittsburgh Penguins,right,New York Islanders,Goal,Shot,Wrist Shot,...,False,Matt Cullen,Thomas Greiss,-67.0,60.0,12.0,-16.0,0,4,4
7311,2015020978,R,102,101,Arizona Coyotes,right,Florida Panthers,Goal,Takeaway,Wrist Shot,...,False,Jordan Martinook,Al Montoya,-69.0,20.0,-10.0,-17.0,0,5,5
8971,2015021017,R,103,102,Calgary Flames,left,Arizona Coyotes,Goal,Takeaway,Snap Shot,...,False,Mikael Backlund,Louis Domingue,78.0,16.0,7.0,-38.0,0,5,5
12546,2015021186,R,191,190,St. Louis Blues,left,Arizona Coyotes,Goal,Faceoff,Wrist Shot,...,False,Kyle Brodziak,Mike Smith,76.0,-69.0,-7.0,22.0,0,5,5
13459,2015020914,R,151,150,Vancouver Canucks,left,Ottawa Senators,Goal,Blocked Shot,Wrist Shot,...,False,Mark Stone,Ryan Miller,-64.0,58.0,-21.0,-4.0,0,4,4
18554,2015021206,R,110,109,Washington Capitals,left,Pittsburgh Penguins,Goal,Shot,Backhand,...,False,Matt Cullen,Braden Holtby,-78.0,52.0,10.0,23.0,0,5,5
20989,2015020495,R,29,28,Tampa Bay Lightning,left,Ottawa Senators,Goal,Giveaway,Backhand,...,False,Zack Smith,Ben Bishop,-58.0,15.0,18.0,-32.0,0,5,5
26241,2015020837,R,187,186,Detroit Red Wings,right,Boston Bruins,Goal,Hit,Wrist Shot,...,False,Joonas Kemppainen,Petr Mrazek,61.0,-82.0,18.0,39.0,0,5,5
28372,2015020089,R,144,143,Boston Bruins,right,Philadelphia Flyers,Goal,Faceoff,Tip-In,...,False,Chris Kelly,Steve Mason,-84.0,20.0,4.0,22.0,0,5,5
32202,2015021047,R,278,277,Buffalo Sabres,left,Montréal Canadiens,Goal,Faceoff,Wrist Shot,...,False,Marcus Foligno,Ben Scrivens,65.0,-69.0,-9.0,22.0,0,5,5
32949,2015021114,R,57,56,St. Louis Blues,left,Vancouver Canucks,Goal,Giveaway,Tip-In,...,False,Kyle Brodziak,Jacob Markstrom,85.0,-38.0,-8.0,-3.0,0,4,4
37123,2015020897,R,226,225,Tampa Bay Lightning,right,Arizona Coyotes,Goal,Penalty,Wrist Shot,...,False,Cedric Paquette,Louis Domingue,-67.0,4.0,1.0,-2.0,0,5,5
41836,2015020874,R,149,148,Pittsburgh Penguins,right,Tampa Bay Lightning,Goal,Faceoff,Backhand,...,False,Tom Kuhnhackl,Ben Bishop,-76.0,69.0,-2.0,22.0,0,4,4
51927,2015021182,R,210,209,Anaheim Ducks,left,Dallas Stars,Goal,Giveaway,Wrist Shot,...,False,Ryan Kesler,Antti Niemi,76.0,76.0,-4.0,34.0,0,5,5
58317,2015020777,R,251,250,Montréal Canadiens,right,Edmonton Oilers,Goal,Giveaway,Backhand,...,False,Benoit Pouliot,Ben Scrivens,80.0,-73.0,-5.0,-40.0,0,5,5
68704,2015020717,R,187,186,Dallas Stars,left,Colorado Avalanche,Goal,Blocked Shot,Wrist Shot,...,False,Gabriel Landeskog,Antti Niemi,-75.0,76.0,6.0,6.0,0,5,5
81617,2016020849,R,231,230,New York Islanders,left,New York Rangers,Goal,Shot,Wrist Shot,...,False,Nikolay Kulemin,Henrik Lundqvist,74.0,75.0,-1.0,-7.0,0,5,5
84311,2016020720,R,49,48,Nashville Predators,left,Buffalo Sabres,Goal,Giveaway,Wrist Shot,...,False,Filip Forsberg,Robin Lehner,68.0,-34.0,6.0,-36.0,0,4,4
84480,2016021131,R,253,252,Toronto Maple Leafs,right,Florida Panthers,Goal,Faceoff,Snap Shot,...,False,Zach Hyman,Reto Berra,-71.0,69.0,-3.0,22.0,0,4,4
84862,2016020327,R,365,364,Philadelphia Flyers,right,Calgary Flames,Goal,Shot,Snap Shot,...,False,Alex Chiasson,Anthony Stolarz,76.0,64.0,7.0,-24.0,0,5,5
85854,2016021058,R,344,343,Carolina Hurricanes,right,Nashville Predators,Goal,Missed Shot,Wrist Shot,...,True,Elias Lindholm,NaN,-52.0,32.0,-3.0,-23.0,0,5,5
90208,2016020700,R,250,249,Calgary Flames,right,Edmonton Oilers,Goal,Faceoff,Wrist Shot,...,False,Sean Monahan,Laurent Brossoit,-61.0,0.0,-3.0,0.0,0,5,5
94383,2016020834,R,89,88,Columbus Blue Jackets,right,New York Rangers,Goal,Faceoff,Wrist Shot,...,False,Dan Girardi,Sergei Bobrovsky,42.0,0.0,-3.0,0.0,0,5,5
101476,2016020443,R,213,212,Calgary Flames,right,Tampa Bay Lightning,Goal,Shot,Wrist Shot,...,False,Alex Killorn,Brian Elliott,80.0,49.0,7.0,15.0,0,5,5
105618,2016020028,R,115,114,Arizona Coyotes,right,Philadelphia Flyers,Goal,Takeaway,Wrist Shot,...,False,Brad Richardson,Steve Mason,-73.0,-12.0,1.0,39.0,0,5,5
107290,2016021176,R,121,120,Buffalo Sabres,right,Toronto Maple Leafs,Goal,Giveaway,Snap Shot,...,False,Ryan O'Reilly,Frederik Andersen,-71.0,49.0,29.0,40.0,0,5,5
131424,2016020105,R,247,246,Los Angeles Kings,right,Nashville Predators,Goal,Giveaway,Wrist Shot,...,False,Viktor Arvidsson,Peter Budaj,59.0,-31.0,-14.0,-16.0,0,5,5
137634,2016020099,R,258,257,Philadelphia Flyers,right,Arizona Coyotes,Goal,Stoppage,Wrist Shot,...,False,Brad Richardson,Steve Mason,85.0,NaN,-1.0,NaN,99,5,4
137830,2016020076,R,120,119,Los Angeles Kings,left,Vancouver Canucks,Goal,Shot,Wrist Shot,...,False,Dustin Brown,Jacob Markstrom,84.0,78.0,-1.0,0.0,0,5,5
138108,2016020922,R,141,140,Boston Bruins,right,Arizona Coyotes,Goal,Takeaway,Wrist Shot,...,False,Riley Nash,Mike Smith,-57.0,-77.0,5.0,39.0,0,5,5
159103,2017021071,R,261,260,Carolina Hurricanes,right,Boston Bruins,Goal,Shot,Wrist Shot,...,False,Brock McGinn,Tuukka Rask,-81.0,-81.0,2.0,1.0,0,5,5
161418,2017020898,R,147,146,Tampa Bay Lightning,right,New Jersey Devils,Goal,Shot,Wrist Shot,...,False,Pavel Zacha,Andrei Vasilevskiy,63.0,51.0,5.0,-32.0,0,4,4
167063,2017020713,R,232,231,Ottawa Senators,right,Toronto Maple Leafs,Goal,Shot,Wrist Shot,...,False,Tom Pyatt,Frederik Andersen,-67.0,50.0,-10.0,13.0,0,4,4
168871,2017020928,R,236,235,Anaheim Ducks,left,Dallas Stars,Goal,Takeaway,Wrist Shot,...,False,Ryan Getzlaf,Ben Bishop,87.0,-42.0,19.0,0.0,0,5,5
169438,2017020020,R,139,138,New York Islanders,right,Buffalo Sabres,Goal,Giveaway,Wrist Shot,...,False,John Tavares,Robin Lehner,-81.0,-42.0,-1.0,-21.0,0,4,4
169440,2017020020,R,143,142,New York Islanders,right,Buffalo Sabres,Goal,Shot,Slap Shot,...,False,Casey Cizikas,Robin Lehner,-68.0,65.0,-11.0,1.0,0,4,4
172454,2017020260,R,351,350,San Jose Sharks,left,Vancouver Canucks,Goal,Takeaway,Wrist Shot,...,True,Chris Tierney,NaN,27.0,10.0,30.0,38.0,0,5,5
172455,2017020260,R,356,355,San Jose Sharks,left,Vancouver Canucks,Goal,Penalty,Wrist Shot,...,False,Chris Tierney,Jacob Markstrom,81.0,14.0,-1.0,-8.0,0,5,5
175116,2017020981,R,73,72,Colorado Avalanche,right,Calgary Flames,Goal,Takeaway,Backhand,...,False,Mikael Backlund,Semyon Varlamov,84.0,-32.0,-7.0,36.0,0,4,4
190010,2017020777,R,114,113,Buffalo Sabres,right,Florida Panthers,Goal,Shot,Wrist Shot,...,False,Zemgus Girgensons,Harri Sateri,-58.0,-55.0,-5.0,25.0,0,5,5
194698,2017021214,R,216,215,Dallas Stars,right,Minnesota Wild,Goal,Giveaway,Tip-In,...,False,Radek Faksa,Devan Dubnyk,-72.0,-5.0,4.0,22.0,0,5,5
196426,2017020106,R,213,212,Detroit Red Wings,right,Washington Capitals,Goal,Blocked Shot,Wrist Shot,...,False,Jay Beagle,Petr Mrazek,78.0,-74.0,-3.0,20.0,0,5,5
220009,2017020248,R,217,216,Vegas Golden Knights,NaN,Winnipeg Jets,Goal,Faceoff,Backhand,...,False,William Karlsson,Connor Hellebuyck,73.0,-69.0,3.0,22.0,0,4,4
229668,2017021182,R,241,240,Winnipeg Jets,right,Boston Bruins,Goal,Giveaway,Wrap-around,...,False,Brandon Tanev,Anton Khudobin,-85.0,-55.0,7.0,24.0,0,5,5
231184,2018020391,R,95,94,Washington Capitals,left,New Jersey Devils,Goal,Faceoff,Wrist Shot,...,False,Tom Wilson,Keith Kinkaid,86.0,0.0,-21.0,0.0,0,5,5
234534,2018020651,R,124,123,Anaheim Ducks,left,Edmonton Oilers,Goal,Takeaway,Backhand,...,False,Kyle Brodziak,John Gibson,-78.0,31.0,0.0,-27.0,0,3,3
248781,2018021256,R,242,241,Anaheim Ducks,left,Los Angeles Kings,Goal,Shot,Tip-In,...,False,Sam Steel,Jack Campbell,80.0,-40.0,4.0,7.0,0,5,5
258206,2018020745,R,224,223,St. Louis Blues,left,Ottawa Senators,Goal,Faceoff,Deflected,...,False,Magnus Paajarvi,Jordan Binnington,-79.0,-20.0,1.0,22.0,0,5,5
268184,2018021159,R,114,113,St. Louis Blues,right,Tampa Bay Lightning,Goal,Faceoff,Backhand,...,False,Alex Killorn,Jordan Binnington,80.0,69.0,-2.0,22.0,0,5,5
269590,2018020772,R,302,301,Pittsburgh Penguins,left,New Jersey Devils,Goal,Giveaway,Wrist Shot,...,False,Matt Cullen,Keith Kinkaid,84.0,94.0,-10.0,2.0,0,5,5
280440,2018020402,R,242,241,Pittsburgh Penguins,left,Philadelphia Flyers,Goal,Giveaway,Wrist Shot,...,False,Dale Weise,Casey DeSmith,-72.0,-40.0,5.0,36.0,0,5,5
281274,2018020455,R,219,218,Winnipeg Jets,left,Philadelphia Flyers,Goal,Shot,Backhand,...,False,Blake Wheeler,Anthony Stolarz,81.0,-58.0,2.0,23.0,0,4,4
283748,2018020316,R,174,173,Vancouver Canucks,left,Winnipeg Jets,Goal,Blocked Shot,Wrist Shot,...,False,Tyler Motte,Connor Hellebuyck,70.0,-55.0,1.0,-1.0,75,5,4
292430,2018020983,R,136,135,Anaheim Ducks,right,Chicago Blackhawks,Goal,Takeaway,Wrist Shot,...,False,Devin Shore,Corey Crawford,-73.0,-54.0,5.0,-8.0,0,5,5
296818,2018020560,R,140,139,Carolina Hurricanes,left,Boston Bruins,Goal,Takeaway,Snap Shot,...,False,Sebastian Aho,Tuukka Rask,59.0,67.0,10.0,38.0,0,5,5
305439,2018020404,R,60,59,Nashville Predators,left,Chicago Blackhawks,Goal,Shot,Deflected,...,False,Brandon Saad,Pekka Rinne,-84.0,42.0,1.0,20.0,0,5,5
306688,2018020280,R,107,106,Columbus Blue Jackets,right,Florida Panthers,Goal,Takeaway,Wrist Shot,...,False,Cam Atkinson,Roberto Luongo,-74.0,35.0,-14.0,-13.0,0,5,5

We notice that our implementation of penalty features has a maximal error rate of 7% on goals (the only way to check correctness based on the data is to check the consistency of our output with the column "Power Game", which contains information on whether the current scoring team is shorthanded, on power play, or in an even situation with the opponent. This information is available only for events of type "Goal"). The error that we have is due to simplification assumptions that were done to count the penalties (each time such an assumption was made, we disscussed it and described it above), and they are based on instructor's answers on piazza.

#### Data importing from util package

The new columns that were created in this notebook will be merged in a new data frame containing all important features. This data frame will be used for training the models in part 3, 5 and 6. In the following cell we import this data frame.

In [35]:
from util.data_aquisition import generate
from util.engineered_data_frame import engineered_data_frame

In [2]:
data = generate(seasons=[2015, 2016, 2017, 2018], play_offs=[False])

Data is available on your system. Will be loaded from: /Users/nassimwalha/Desktop/IFT-6758/data/regular_season/2015-2016
Data is available on your system. Will be loaded from: /Users/nassimwalha/Desktop/IFT-6758/data/regular_season/2016-2017
Data is available on your system. Will be loaded from: /Users/nassimwalha/Desktop/IFT-6758/data/regular_season/2017-2018
Data is available on your system. Will be loaded from: /Users/nassimwalha/Desktop/IFT-6758/data/regular_season/2018-2019

In [36]:
df = engineered_data_frame(data)
df

/Users/nassimwalha/Desktop/IFT-6758/notebooks/util/engineered_data_frame.py:75: RuntimeWarning: invalid value encountered in double_scalars
  return 90*row['Y_Coordinate']/(np.abs(row['Y_Coordinate']))

,Game_ID,Game_Type,Event_ID,Last_Event_ID,Home_Team,Home_Rink,Away_Team,Event_Type,Last_Event_Type,Shoot_Type,...,Time_Between_Events,X_Transformed,Last_X_Transformed,Distance_Last_Event,Distance_Net,Rebond,Angle,Last_Angle,Delta_Angle,Speed
0,2015020364,R,5,4,Nashville Predators,left,Arizona Coyotes,Shot,Hit,Wrist Shot,...,6,50.0,-78.0,140.527577,43.829214,False,27.149682,0.000000,27.149682,23.421263
1,2015020364,R,12,10,Nashville Predators,left,Arizona Coyotes,Shot,Faceoff,Wrist Shot,...,29,77.0,69.0,29.120440,13.416408,False,26.565051,0.000000,26.565051,1.004153
2,2015020364,R,13,11,Nashville Predators,left,Arizona Coyotes,Shot,Takeaway,Wrist Shot,...,7,86.0,35.0,51.971146,12.369317,False,-75.963757,0.000000,-75.963757,7.424449
3,2015020364,R,18,17,Nashville Predators,left,Arizona Coyotes,Shot,Faceoff,Backhand,...,10,82.0,69.0,19.849433,9.899495,False,45.000000,0.000000,45.000000,1.984943
4,2015020364,R,32,31,Nashville Predators,left,Arizona Coyotes,Shot,Blocked Shot,Wrist Shot,...,23,48.0,85.0,37.013511,42.201896,False,-13.706961,0.000000,-13.706961,1.609283
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
311101,2018021002,R,285,284,Toronto Maple Leafs,right,Buffalo Sabres,Shot,Shot,Wrist Shot,...,11,47.0,-75.0,122.690668,43.965896,True,17.198541,0.000000,17.198541,11.153697
311102,2018021002,R,286,285,Toronto Maple Leafs,right,Buffalo Sabres,Shot,Shot,Backhand,...,8,74.0,-47.0,121.926207,15.132746,True,-7.594643,5.460213,-13.054856,15.240776
311103,2018021002,R,287,286,Toronto Maple Leafs,right,Buffalo Sabres,Shot,Shot,Wrist Shot,...,2,78.0,74.0,8.062258,12.083046,True,24.443955,-7.594643,32.038598,4.031129
311104,2018021002,R,292,291,Toronto Maple Leafs,right,Buffalo Sabres,Goal,Takeaway,Backhand,...,43,68.0,-96.0,164.027437,40.816663,False,59.036243,0.000000,59.036243,3.814592
311105,2018021002,R,296,295,Toronto Maple Leafs,right,Buffalo Sabres,Shot,Blocked Shot,Wrist Shot,...,5,43.0,64.0,33.421550,47.539457,False,-14.620874,0.000000,-14.620874,6.684310

In [37]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 311106 entries, 0 to 311105
Data columns (total 39 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   Game_ID                   311106 non-null  int64
 1   Game_Type                 311106 non-null  object
 2   Event_ID                  311106 non-null  int64
 3   Last_Event_ID             311106 non-null  int64
 4   Home_Team                 311106 non-null  object
 5   Home_Rink                 303529 non-null  object
 6   Away_Team                 311106 non-null  object
 7   Event_Type                311106 non-null  object
 8   Last_Event_Type           311106 non-null  object
 9   Shoot_Type                311068 non-null  object
 10  Time                      311106 non-null  object
 11  Period                    311106 non-null  int64
 12  Last_Period               311106 non-null  int64
 13  Period_Time               311106 non-null  object
 14  Last_Period_Time          311106 non-null  object
 15  Team_Attack               311106 non-null  object
 16  Power_Game                29187 non-null   object
 17  Empty_Net                 28295 non-null   object
 18  Shooters_scorer           311106 non-null  object
 19  Goalies                   309683 non-null  object
 20  X_Coordinate              311088 non-null  float64
 21  Last_Coordinate_X         306148 non-null  float64
 22  Y_Coordinate              311088 non-null  float64
 23  Last_Coordinate_Y         306149 non-null  float64
 24  Powerplay_Since           311106 non-null  object
 25  Friendly_Non_Goalies      311106 non-null  int64
 26  Opponent_Non_Goalies      311106 non-null  int64
 27  Period_Time_Seconds       311106 non-null  int64
 28  Last_Period_Time_Seconds  311106 non-null  int64
 29  Time_Between_Events       311106 non-null  int64
 30  X_Transformed             311088 non-null  float64
 31  Last_X_Transformed        306148 non-null  float64
 32  Distance_Last_Event       306133 non-null  float64
 33  Distance_Net              311086 non-null  float64
 34  Rebond                    311106 non-null  bool
 35  Angle                     311085 non-null  float64
 36  Last_Angle                311099 non-null  float64
 37  Delta_Angle               311081 non-null  float64
 38  Speed                     306112 non-null  float64
dtypes: bool(1), float64(12), int64(10), object(16)
memory usage: 90.5+ MB

In [38]:
df.columns

Index(['Game_ID', 'Game_Type', 'Event_ID', 'Last_Event_ID', 'Home_Team',
       'Home_Rink', 'Away_Team', 'Event_Type', 'Last_Event_Type', 'Shoot_Type',
       'Time', 'Period', 'Last_Period', 'Period_Time', 'Last_Period_Time',
       'Team_Attack', 'Power_Game', 'Empty_Net', 'Shooters_scorer', 'Goalies',
       'X_Coordinate', 'Last_Coordinate_X', 'Y_Coordinate',
       'Last_Coordinate_Y', 'Powerplay_Since', 'Friendly_Non_Goalies',
       'Opponent_Non_Goalies', 'Period_Time_Seconds',
       'Last_Period_Time_Seconds', 'Time_Between_Events', 'X_Transformed',
       'Last_X_Transformed', 'Distance_Last_Event', 'Distance_Net', 'Rebond',
       'Angle', 'Last_Angle', 'Delta_Angle', 'Speed'],
      dtype='object')

#### Data submission to comet.ml (question 4)

In [1]:
from comet_ml import  Experiment
from util.data_aquisition import generate
from util.engineered_data_frame import engineered_data_frame

In [2]:
import os

In [3]:
data = generate(seasons=[2017], play_offs=[False])
df =engineered_data_frame(data)

Data is available on your system. Will be loaded from: /Users/nassimwalha/Desktop/IFT-6758/data/regular_season/2017-2018

/Users/nassimwalha/Desktop/IFT-6758/notebooks/util/engineered_data_frame.py:75: RuntimeWarning: invalid value encountered in double_scalars
  return 90*row['Y_Coordinate']/(np.abs(row['Y_Coordinate']))

In [4]:
df =df[df["Game_ID"]==2017021065]

In [5]:
exp = Experiment(api_key=os.environ.get("COMET_API_KEY"), workspace="nassim-walha", project_name="ds-milestone2")
exp.add_tag("Data")
exp.log_dataframe_profile(
    df,
    name='wpg_v_wsh_2017021065',  # keep this name
    dataframe_format='csv'  # ensure you set this flag!
)

COMET WARNING: As you are running in a Jupyter environment, you will need to call `experiment.end()` when finished to ensure all metrics and code are logged before exiting.
COMET INFO: Experiment is live on comet.com https://www.comet.com/nassim-walha/ds-milestone2/5c1588c8706d4862ba72f7cf4862befb

COMET WARNING: pandas_profiling is required to log profile; ignoring

{'profile': None,
 'dataframe': {'web': 'https://www.comet.com/api/asset/download?assetId=64a2a3ab8064463ab6cc73c04ff7e199&experimentKey=5c1588c8706d4862ba72f7cf4862befb',
  'api': 'https://www.comet.com/api/rest/v2/experiment/asset/get-asset?assetId=64a2a3ab8064463ab6cc73c04ff7e199&experimentKey=5c1588c8706d4862ba72f7cf4862befb',
  'assetId': '64a2a3ab8064463ab6cc73c04ff7e199'}}

In [6]:
exp.end()

COMET INFO: ---------------------------
COMET INFO: Comet.ml Experiment Summary
COMET INFO: ---------------------------
COMET INFO:   Data:
COMET INFO:     display_summary_level : 1
COMET INFO:     url                   : https://www.comet.com/nassim-walha/ds-milestone2/5c1588c8706d4862ba72f7cf4862befb
COMET INFO:   Uploads:
COMET INFO:     conda-environment-definition : 1
COMET INFO:     conda-info                   : 1
COMET INFO:     conda-specification          : 1
COMET INFO:     dataframe                    : 1 (23.22 KB)
COMET INFO:     environment details          : 1
COMET INFO:     filename                     : 1
COMET INFO:     git metadata                 : 1
COMET INFO:     git-patch (uncompressed)     : 1 (204.81 KB)
COMET INFO:     installed packages           : 1
COMET INFO:     notebook                     : 1
COMET INFO:     source_code                  : 1
COMET INFO: ---------------------------
COMET INFO: Uploading metrics, params, and assets to Comet before program termination (may take several seconds)
COMET INFO: The Python SDK has 3600 seconds to finish before aborting...
COMET INFO: Waiting for completion of the file uploads (may take several seconds)
COMET INFO: The Python SDK has 10800 seconds to finish before aborting...
COMET INFO: All files uploaded, waiting for confirmation they have been all received